Version bump to x.75.5 before release
We had to delete the upstream test-suite check because they
broke their compatibility with UbuntuLTS' NodeJS version (more
info about this in upstream issue number 4849).

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -38,18 +38,18 @@ jobs:
           echo "Package.json version: $PKG_VERSION"
 
           # Compare versions
-          #if [ "$TAG_VERSION" != "$PKG_VERSION" ]; then
-          #  echo "ERROR: Git tag version ($TAG_VERSION) does not match package.json version ($PKG_VERSION)"
-          #  exit 1
-          #fi
+          if [ "$TAG_VERSION" != "$PKG_VERSION" ]; then
+            echo "ERROR: Git tag version ($TAG_VERSION) does not match package.json version ($PKG_VERSION)"
+            exit 1
+          fi
 
-          #PKG_MINOR_PATCH="${PKG_VERSION#*.}"
-          #PI_MINOR_PATCH="${PI_VERSION#*.}"
+          PKG_MINOR_PATCH="${PKG_VERSION#*.}"
+          PI_MINOR_PATCH="${PI_VERSION#*.}"
 
-          #if [ "$PKG_MINOR_PATCH" != "$PI_MINOR_PATCH" ]; then
-          #    echo "Minor and patch components of package.json version ($PKG_VERSION) are different from corresponding components of pi version ($PI_VERSION)"
-          #    exit 1
-          #fi
+          if [ "$PKG_MINOR_PATCH" != "$PI_MINOR_PATCH" ]; then
+              echo "Minor and patch components of package.json version ($PKG_VERSION) are different from corresponding components of pi version ($PI_VERSION)"
+              exit 1
+          fi
 
           #echo "✓ Versions match!"
 
